"""Tests for the QuickNode Streams filter design (Stream Latency task 3).

Two layers:
  1. ``render_filter`` (pure Python template render) — no DB, no subprocess.
  2. The rendered filter's actual JAVASCRIPT behavior, executed for real via Node.js
     (not a Python re-implementation that could silently drift from the deployed
     filter) — proving the evidence-completeness contract task 3 requires:
     "Stream filtering cannot remove required evidence" and never hardcodes an
     address (the list is always a render_filter() parameter, sourced from the DB
     by the generator script, never typed into application/test source as a
     literal the filter logic depends on).
"""
from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path

import pytest

from services.api.scripts.generate_quicknode_stream_filter import render_filter

pytestmark = pytest.mark.skipif(shutil.which('node') is None, reason='Node.js not available to execute the generated filter')

MONITORED = '0x5f6f35fd8b10c5576089f99c7c8c351deb851d1f'
OTHER_MONITORED = '0x' + 'ab' * 20
UNRELATED_A = '0x' + '11' * 20
UNRELATED_B = '0x' + '22' * 20


def _run_filter(addresses: list[str], block_entry: dict) -> dict | None:
    """Render the filter for ``addresses`` and execute it via Node.js against
    ``block_entry`` (a single ``{block, receipts}`` dataset entry), returning the
    filter's actual JS return value.

    Wrapped in a single-element list to match QuickNode's real "Block with
    Receipts" batch_size=1 delivery shape (see _extract_tx_dicts / the profiling
    test's ``_make_realistic_base_block_payload``: production payloads are a
    one-element top-level array, never a bare object)."""
    rendered = render_filter(addresses, generated_at='2026-08-25T00:00:00+00:00')
    stream_payload = [block_entry]
    script = rendered + f'\nconsole.log(JSON.stringify(main({json.dumps(stream_payload)})));\n'
    tmp_path = Path(__file__).parent / '_tmp_quicknode_filter_check.js'
    tmp_path.write_text(script, encoding='utf-8')
    try:
        result = subprocess.run(
            ['node', str(tmp_path)], capture_output=True, text=True, timeout=10, check=True,
        )
    finally:
        tmp_path.unlink(missing_ok=True)
    stdout = result.stdout.strip()
    return json.loads(stdout) if stdout and stdout != 'null' else None


def _sample_tx(*, tx_hash: str, from_addr: str, to_addr: str, value: str = '0x1') -> dict:
    return {
        'hash': tx_hash, 'from': from_addr, 'to': to_addr, 'value': value,
        'input': '0xdeadbeef', 'gas': '0x5208', 'gasPrice': '0x3b9aca00', 'nonce': '0x1',
    }


def _sample_receipt(*, tx_hash: str, status: str = '0x1') -> dict:
    return {
        'transactionHash': tx_hash, 'status': status, 'gasUsed': '0x5208',
        'logs': [{'address': UNRELATED_A, 'topics': ['0xabc'], 'data': '0x01'}],
    }


def test_render_filter_embeds_lowercase_address_list():
    rendered = render_filter([MONITORED.upper()])
    assert MONITORED in rendered  # lowercased even if the source data was not
    assert 'GENERATED by services/api/scripts/generate_quicknode_stream_filter.py' in rendered


def test_render_filter_is_syntactically_valid_javascript():
    rendered = render_filter([MONITORED])
    tmp_path = Path(__file__).parent / '_tmp_quicknode_filter_syntax.js'
    tmp_path.write_text(rendered, encoding='utf-8')
    try:
        subprocess.run(['node', '--check', str(tmp_path)], capture_output=True, text=True, timeout=10, check=True)
    finally:
        tmp_path.unlink(missing_ok=True)


def test_filter_drops_block_with_no_monitored_transactions():
    payload = {
        'block': {'number': '0x3', 'timestamp': '0x1', 'transactions': [
            _sample_tx(tx_hash='0xaaa', from_addr=UNRELATED_A, to_addr=UNRELATED_B),
        ]},
        'receipts': [_sample_receipt(tx_hash='0xaaa')],
    }
    assert _run_filter([MONITORED], payload) is None


def test_filter_keeps_matched_tx_with_full_evidence_and_drops_the_rest():
    matched = _sample_tx(tx_hash='0xmatched', from_addr=MONITORED, to_addr=UNRELATED_B, value='0xde0b6b3a7640000')
    unrelated = _sample_tx(tx_hash='0xunrelated', from_addr=UNRELATED_A, to_addr=UNRELATED_B)
    payload = {
        'block': {'number': '0x3123456', 'timestamp': '0x6710f001', 'transactions': [unrelated, matched]},
        'receipts': [_sample_receipt(tx_hash='0xunrelated'), _sample_receipt(tx_hash='0xmatched', status='0x1')],
    }
    result = _run_filter([MONITORED], payload)
    assert result is not None
    assert result['block']['number'] == '0x3123456'
    assert result['block']['timestamp'] == '0x6710f001'
    # Exactly the matched tx survives, unrelated tx/receipt is gone.
    assert [tx['hash'] for tx in result['block']['transactions']] == ['0xmatched']
    assert [r['transactionHash'] for r in result['receipts']] == ['0xmatched']
    # Required evidence fields task 3 lists are all present, unreduced, on the kept tx.
    kept = result['block']['transactions'][0]
    for field in ('hash', 'from', 'to', 'value'):
        assert kept[field] == matched[field]
    kept_receipt = result['receipts'][0]
    assert kept_receipt['status'] == '0x1'
    assert kept_receipt['logs'] == _sample_receipt(tx_hash='0xmatched')['logs']


def test_filter_matches_on_to_address_as_well_as_from():
    matched = _sample_tx(tx_hash='0xin', from_addr=UNRELATED_A, to_addr=MONITORED)
    payload = {
        'block': {'number': '0x1', 'timestamp': '0x1', 'transactions': [matched]},
        'receipts': [_sample_receipt(tx_hash='0xin')],
    }
    result = _run_filter([MONITORED], payload)
    assert result is not None
    assert [tx['hash'] for tx in result['block']['transactions']] == ['0xin']


def test_filter_matching_is_case_insensitive():
    matched = _sample_tx(tx_hash='0xcasing', from_addr=MONITORED.upper(), to_addr=UNRELATED_B)
    payload = {
        'block': {'number': '0x1', 'timestamp': '0x1', 'transactions': [matched]},
        'receipts': [_sample_receipt(tx_hash='0xcasing')],
    }
    result = _run_filter([MONITORED], payload)  # allowlist stored lowercase
    assert result is not None
    assert [tx['hash'] for tx in result['block']['transactions']] == ['0xcasing']


def test_filter_supports_multiple_monitored_addresses():
    """Multi-workspace readiness: the filter is never limited to one wallet."""
    tx_a = _sample_tx(tx_hash='0xa', from_addr=MONITORED, to_addr=UNRELATED_A)
    tx_b = _sample_tx(tx_hash='0xb', from_addr=OTHER_MONITORED, to_addr=UNRELATED_A)
    tx_c = _sample_tx(tx_hash='0xc', from_addr=UNRELATED_A, to_addr=UNRELATED_B)
    payload = {
        'block': {'number': '0x1', 'timestamp': '0x1', 'transactions': [tx_a, tx_b, tx_c]},
        'receipts': [_sample_receipt(tx_hash=h) for h in ('0xa', '0xb', '0xc')],
    }
    result = _run_filter([MONITORED, OTHER_MONITORED], payload)
    assert result is not None
    assert sorted(tx['hash'] for tx in result['block']['transactions']) == ['0xa', '0xb']


def test_generator_never_hardcodes_an_address_in_application_source():
    """The filter body itself (independent of any addresses passed to it) must not
    contain a literal wallet address — the allowlist is always a render_filter()
    input, sourced at generation time from the database, never a source-code literal."""
    import re
    from services.api.scripts import generate_quicknode_stream_filter as gen_module

    source = Path(gen_module.__file__).read_text(encoding='utf-8')
    assert not re.search(r'0x[0-9a-fA-F]{40}', source), 'generator source must not contain a literal wallet address'


def test_main_writes_filter_and_address_files(tmp_path, monkeypatch):
    from services.api.scripts import generate_quicknode_stream_filter as gen_module

    monkeypatch.setattr(gen_module, '_load_monitored_base_addresses', lambda: [MONITORED, OTHER_MONITORED])
    out_dir = tmp_path / 'quicknode_filters'
    rc = gen_module.main(['--out-dir', str(out_dir)])
    assert rc == 0
    filter_js = (out_dir / 'base_live_filter.js').read_text(encoding='utf-8')
    assert MONITORED in filter_js
    addresses = json.loads((out_dir / 'monitored_addresses.json').read_text(encoding='utf-8'))
    assert sorted(addresses['addresses']) == sorted([MONITORED, OTHER_MONITORED])


def test_main_reports_failure_when_no_addresses_resolved(monkeypatch, capsys):
    from services.api.scripts import generate_quicknode_stream_filter as gen_module

    monkeypatch.setattr(gen_module, '_load_monitored_base_addresses', lambda: [])
    rc = gen_module.main(['--stdout'])
    assert rc == 1
    assert 'nothing to generate' in capsys.readouterr().err
