#!/usr/bin/env python3
"""Write services/api/artifacts/live_evidence/latest/summary.json from existing proof records.

This script derives a truthful summary from the live_proof/ records that were
previously generated by export_live_proof_artifact_set.py.  It does not require
the full services.api app stack (no fastapi / database required).

live_evidence_ready is true only if ALL required proof records exist and parse.
Fail-closed: any missing or unparseable record → live_evidence_ready=False.
"""
from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
LIVE_EVIDENCE_DIR = REPO_ROOT / 'services' / 'api' / 'artifacts' / 'live_evidence' / 'latest'
ARTIFACT_DIR = LIVE_EVIDENCE_DIR / 'live_proof'

REQUIRED_PROOF_RECORDS = (
    'chain_evidence_detection_alert_incident.json',
    'evidence_metadata_verification.json',
    'live_action_execution.json',
    'incident_timeline_action_metadata.json',
)


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def main() -> int:
    missing_reasons: list[str] = []
    parsed: dict[str, object] = {}

    for record in REQUIRED_PROOF_RECORDS:
        record_path = ARTIFACT_DIR / record
        if not record_path.exists():
            missing_reasons.append(f'missing_proof_record:{record}')
            continue
        try:
            parsed[record] = json.loads(record_path.read_text(encoding='utf-8'))
        except Exception as exc:
            missing_reasons.append(f'parse_failure:{record}:{exc}')

    live_evidence_ready = not missing_reasons

    chain = parsed.get('chain_evidence_detection_alert_incident.json') or {}
    chain = chain if isinstance(chain, dict) else {}
    evidence = chain.get('evidence') if isinstance(chain.get('evidence'), dict) else {}
    evidence_origin = str(evidence.get('origin') or '').strip().lower()

    action = parsed.get('live_action_execution.json') or {}
    action = action if isinstance(action, dict) else {}
    executed_at = str(action.get('executed_at') or '').strip() or None
    external_reference = str(action.get('external_reference') or '').strip()

    summary: dict[str, object] = {
        'generated_at': _now_iso(),
        'evidence_source': evidence_origin or 'unknown',
        'telemetry_evidence_source': evidence_origin if evidence_origin else 'unknown',
        'live_evidence_ready': live_evidence_ready,
        'provider_ready': live_evidence_ready,
        'missing_reasons': missing_reasons,
        'latest_live_telemetry_at': executed_at,
        # Boolean fields required by validate_readiness_proof.py
        'live_successful_monitoring_demo': live_evidence_ready and evidence_origin == 'live',
        'simulator_successful_monitoring_demo': False,
        'telemetry_event_present': bool(chain.get('evidence')),
        'detection_generated_from_telemetry': bool(chain.get('detection')),
        'alert_generated_from_detection': bool(chain.get('alert')),
        'incident_opened_from_alert': bool(chain.get('incident')),
        'response_action_recommended_or_executed': bool(external_reference),
        'evidence_package_exported': live_evidence_ready,
        'billing_email_provider_checks_passing': False,
        'onboarding_to_first_signal_complete': live_evidence_ready,
        'production_validation_proof_bundle_complete': False,
        'controlled_pilot_ready': False,
        'enterprise_procurement_ready': False,
        'broad_self_serve_ready': False,
        'broad_self_serve_blocked_reason': 'billing_email_provider_checks_not_confirmed',
        'paid_launch_readiness': {
            'billing_ready': False,
            'billing_webhook_ready': False,
            'email_ready': False,
            'provider_ready': live_evidence_ready,
            'paid_launch_ready': False,
            'blockers': ['billing_not_configured', 'email_not_configured'],
        },
        'claim_ineligibility_reasons': ['billing_not_configured', 'email_not_configured'],
    }

    LIVE_EVIDENCE_DIR.mkdir(parents=True, exist_ok=True)
    out_path = LIVE_EVIDENCE_DIR / 'summary.json'
    out_path.write_text(json.dumps(summary, indent=2, sort_keys=True, default=str), encoding='utf-8')

    status = 'ok' if live_evidence_ready else 'fail_closed'
    print(json.dumps({
        'status': status,
        'live_evidence_ready': live_evidence_ready,
        'missing_reasons': missing_reasons,
        'summary_path': str(out_path.relative_to(REPO_ROOT)),
    }, indent=2))
    return 0 if live_evidence_ready else 1


if __name__ == '__main__':
    raise SystemExit(main())
