"""Generate a QuickNode Streams filter (Stream Latency task 3) from live target data.

Usage:
    python -m services.api.scripts.generate_quicknode_stream_filter [--out-dir DIR]

Reads the SAME active-Base-wallet-target set and wallet resolution the /base-live
webhook itself uses (``quicknode_streams._load_all_base_wallet_targets`` /
``resolve_monitored_wallet``) and emits a ready-to-paste QuickNode Streams filter
function whose address allowlist can never drift from what Decoda actually matches —
see docs/quicknode_stream_filter_design.md for the full design and rationale.

Read-only: this never writes to the database, never calls the QuickNode API, and
never modifies application code or the live filter — it only prints/writes the
generated filter source for a human operator to review and paste into the QuickNode
dashboard (or push to a Key-Value Store, once that option is adopted). Output is
written under services/api/artifacts/quicknode_filters/, which is gitignored,
because it names real monitored wallet addresses.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

_FILTER_TEMPLATE = """\
// QuickNode Streams filter function — Base "Block with Receipts" dataset.
// GENERATED by services/api/scripts/generate_quicknode_stream_filter.py at {generated_at}
// from {target_count} active Base wallet target(s) — do not hand-edit
// MONITORED_ADDRESSES; regenerate it instead so it always matches what Decoda's own
// targets table resolves. See docs/quicknode_stream_filter_design.md.
function main(stream) {{
  const MONITORED_ADDRESSES = new Set({address_list_json});

  const data = stream.data ? stream.data[0] : stream[0];
  if (!data || !data.block || !Array.isArray(data.block.transactions)) return null;

  const matchedHashes = new Set();
  const matchedTxs = data.block.transactions.filter((tx) => {{
    const from = (tx.from || '').toLowerCase();
    const to = (tx.to || '').toLowerCase();
    const hit = MONITORED_ADDRESSES.has(from) || MONITORED_ADDRESSES.has(to);
    if (hit) matchedHashes.add((tx.hash || '').toLowerCase());
    return hit;
  }});

  if (matchedTxs.length === 0) return null;

  const matchedReceipts = Array.isArray(data.receipts)
    ? data.receipts.filter((r) => matchedHashes.has((r.transactionHash || '').toLowerCase()))
    : [];

  return {{
    block: {{
      number: data.block.number,
      timestamp: data.block.timestamp,
      transactions: matchedTxs,
    }},
    receipts: matchedReceipts,
  }};
}}
"""


def _load_monitored_base_addresses() -> list[str]:
    """The exact address set the /base-live webhook currently matches against.

    Imported lazily (fastapi/psycopg not required for --help / tests of the pure
    template logic) and reuses quicknode_streams' own loader + resolver so this
    can never silently drift from the webhook's real matching behavior.
    """
    from services.api.app.pilot import pg_connection
    from services.api.app.quicknode_streams import _load_all_base_wallet_targets
    from services.api.app.evm_activity_provider import resolve_monitored_wallet

    with pg_connection() as connection:
        targets = _load_all_base_wallet_targets(connection)
    addresses = sorted({
        wallet for wallet in (resolve_monitored_wallet(t) for t in targets) if wallet
    })
    return addresses


def render_filter(addresses: list[str], *, generated_at: str | None = None) -> str:
    """Pure (no I/O) template render — the piece under direct test coverage.

    Defensively lowercases every address: the filter's own JS lowercases
    tx.from/tx.to before checking Set membership, so a mixed-case entry here would
    silently never match — never rely on the caller having already normalized.
    """
    generated_at = generated_at or datetime.now(timezone.utc).isoformat()
    normalized = sorted({addr.strip().lower() for addr in addresses if addr and addr.strip()})
    return _FILTER_TEMPLATE.format(
        generated_at=generated_at,
        target_count=len(normalized),
        address_list_json=json.dumps(normalized),
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        '--out-dir', default='services/api/artifacts/quicknode_filters',
        help='Directory to write the generated filter + address list into (gitignored).',
    )
    parser.add_argument(
        '--stdout', action='store_true',
        help='Print the filter to stdout instead of writing files (still no filesystem write).',
    )
    args = parser.parse_args(argv)

    addresses = _load_monitored_base_addresses()
    if not addresses:
        print('No active Base wallet targets resolved a monitored address — nothing to generate.', file=sys.stderr)
        return 1

    rendered = render_filter(addresses)

    if args.stdout:
        print(rendered)
        return 0

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    filter_path = out_dir / 'base_live_filter.js'
    addresses_path = out_dir / 'monitored_addresses.json'
    filter_path.write_text(rendered, encoding='utf-8')
    addresses_path.write_text(json.dumps({'addresses': addresses}, indent=2) + '\n', encoding='utf-8')
    print(f'Wrote {filter_path} ({len(addresses)} address(es)) and {addresses_path}.')
    print('Review both, then paste the filter into the QuickNode Streams dashboard.')
    print('This directory is gitignored — never commit generated filter output.')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
